import subprocess
import zipfile
from pathlib import Path

import pytest

from kimcad import slicer as slicer_mod
from kimcad.config import Config, Material, Printer
from kimcad.slicer import (
    GcodeProofFailed,
    OrcaProfileError,
    SliceFailed,
    SliceSettings,
    SliceTimeout,
    _find_profile_json,
    prove_gcode_3mf,
    resolve_slice_settings,
    slice_model,
)

SETTINGS = SliceSettings(
    machine=Path("machine.json"),
    process=Path("process.json"),
    filament=Path("filament.json"),
)

_GCODE = (
    "; generated by test\n"
    "; total layer number: 100\n"
    "; filament used [mm] = 2582.09\n"
    "; filament used [cm3] = 6.21\n"
    "; filament used [g] = 7.62\n"
    "; model printing time: 14m 31s; total estimated time: 14m 45s\n"
    "G28\n"
    "G1 Z0.2 F300\n"
    "G1 X10 Y10 E1.0\n"
    "G1 X20 Y20 E2.0\n"
)


def _write_gcode_3mf(path: Path, gcode: str = _GCODE, member: str = "Metadata/plate_1.gcode"):
    """Write a minimal but structurally-real OrcaSlicer .gcode.3mf (a zip with an
    embedded per-plate G-code member)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("3D/3dmodel.model", "<model/>")
        if gcode is not None:
            zf.writestr(member, gcode)


def _stub_binary(tmp_path: Path) -> Path:
    """slice_model now refuses a binary that isn't on disk (ToolMissingError, QA-003).
    These tests mock the subprocess layer, so satisfy the guard with a real (empty) file."""
    p = tmp_path / "orca-slicer.exe"
    if not p.exists():
        p.write_bytes(b"")
    return p


def test_slice_builds_expected_command(tmp_path, monkeypatch):
    seen = {}

    def _run(cmd, **kwargs):
        seen["cmd"] = cmd
        _write_gcode_3mf(Path(cmd[cmd.index("--export-3mf") + 1]))
        return subprocess.CompletedProcess(cmd, 0, stdout="ok", stderr="")

    monkeypatch.setattr(slicer_mod.subprocess, "run", _run)
    result = slice_model(
        tmp_path / "part.oriented.stl",
        binary=_stub_binary(tmp_path),
        out_dir=tmp_path,
        settings=SETTINGS,
        basename="part",
    )
    cmd = seen["cmd"]
    assert "--slice" in cmd and "1" in cmd
    assert "machine.json;process.json" in cmd
    assert "--allow-newer-file" in cmd
    assert result.gcode_path.name == "part.gcode.3mf"
    assert result.gcode_path.exists()
    # slice_model proved the toolpath, not just the file's existence
    assert result.gcode_proof is not None
    assert result.gcode_proof.has_motion
    assert result.gcode_proof.line_count >= 4


def test_slice_fails_when_3mf_has_no_gcode(tmp_path, monkeypatch):
    """A zero exit that yields a 3MF with no embedded toolpath is still a failed slice."""
    def _run(cmd, **kwargs):
        _write_gcode_3mf(Path(cmd[cmd.index("--export-3mf") + 1]), gcode=None)
        return subprocess.CompletedProcess(cmd, 0, stdout="ok", stderr="")

    monkeypatch.setattr(slicer_mod.subprocess, "run", _run)
    with pytest.raises(SliceFailed, match="no .gcode toolpath member"):
        slice_model(
            tmp_path / "x.stl", binary=_stub_binary(tmp_path), out_dir=tmp_path, settings=SETTINGS
        )


def test_slice_failed_on_nonzero(tmp_path, monkeypatch):
    def _run(cmd, **kwargs):
        return subprocess.CompletedProcess(cmd, 2, stdout="", stderr="bad profile")

    monkeypatch.setattr(slicer_mod.subprocess, "run", _run)
    with pytest.raises(SliceFailed):
        slice_model(
            tmp_path / "x.stl",
            binary=_stub_binary(tmp_path),
            out_dir=tmp_path,
            settings=SETTINGS,
        )


def test_slice_failed_arrange_message_names_the_footprint(tmp_path, monkeypatch):
    # QA-504: an OrcaSlicer off-bed / can't-arrange failure is logged to STDOUT (stderr empty), so a
    # bare exit code would fall through to the generic "too large or too solid" message that
    # contradicts a green "fits the build plate" gate. The arrange signature must yield an honest
    # footprint-specific reason instead.
    def _run(cmd, **kwargs):
        return subprocess.CompletedProcess(
            cmd,
            4294967246,
            stdout="plate 1: can not be arranged inside plate!\nNothing to be sliced",
            stderr="",
        )

    monkeypatch.setattr(slicer_mod.subprocess, "run", _run)
    with pytest.raises(SliceFailed) as ei:
        slice_model(
            tmp_path / "x.stl", binary=_stub_binary(tmp_path), out_dir=tmp_path, settings=SETTINGS
        )
    msg = str(ei.value)
    assert "footprint" in msg.lower() and "reduce the width/depth" in msg
    assert "too large or too solid" not in msg  # not the generic fallback


def test_slice_failed_message_is_user_legible():
    # QA-003: a Windows unsigned exit code is shown signed, and an empty stderr gets a
    # plain-English hint instead of a bare dangling colon.
    msg = str(SliceFailed(4294967246, ""))
    assert "4294967246" not in msg  # not the raw unsigned value
    assert "-50" in msg  # the signed equivalent
    assert "too large or too solid" in msg  # the plain-English hint (no dangling colon)
    # A real stderr is preserved (signed code still applied).
    assert "bad profile" in str(SliceFailed(2, "bad profile"))


def test_slice_timeout(tmp_path, monkeypatch):
    def _run(cmd, **kwargs):
        raise subprocess.TimeoutExpired(cmd, kwargs.get("timeout", 1))

    monkeypatch.setattr(slicer_mod.subprocess, "run", _run)
    with pytest.raises(SliceTimeout):
        slice_model(
            tmp_path / "x.stl",
            binary=_stub_binary(tmp_path),
            out_dir=tmp_path,
            settings=SETTINGS,
            timeout_s=1,
        )


# --- profile name -> on-disk JSON resolution (Stage 1, Slice 1) ---------------

_PLA = Material(
    key="pla", name="PLA", nozzle_temp=210, bed_temp=55, wall_multiplier=2.0, shrinkage=0.002
)
_PETG = Material(
    key="petg", name="PETG", nozzle_temp=240, bed_temp=75, wall_multiplier=2.5, shrinkage=0.004
)


def _profile_tree(root):
    """Build a minimal shipped-style profile tree and return ``root``."""
    layout = {
        "machine": ["Bambu Lab P2S 0.4 nozzle", "Elegoo Neptune 4 Max (0.4 nozzle)"],
        "process": ["0.20mm Standard @BBL P2S"],
        "filament": ["Bambu PLA Basic @BBL P2S", "Generic PETG", "Generic PLA @Elegoo"],
    }
    for kind, names in layout.items():
        d = root / "BBL" / kind
        d.mkdir(parents=True, exist_ok=True)
        for name in names:
            (d / f"{name}.json").write_text("{}", encoding="utf-8")
    return root


def _p2s(**over):
    base = dict(
        key="bambu_p2s",
        name="Bambu Lab P2S",
        build_volume=(256, 256, 256),
        nozzle_diameter=0.4,
        orca_machine_profile="Bambu Lab P2S 0.4 nozzle",
        orca_process_profile="0.20mm Standard @BBL P2S",
        orca_filament_profiles={"pla": "Bambu PLA Basic @BBL P2S"},
    )
    base.update(over)
    return Printer(**base)


def test_find_profile_json_resolves_by_kind_and_name(tmp_path):
    root = _profile_tree(tmp_path)
    p = _find_profile_json(root, "machine", "Bambu Lab P2S 0.4 nozzle")
    assert p.exists()
    assert "machine" in p.parts and p.stem == "Bambu Lab P2S 0.4 nozzle"


def test_find_profile_json_disambiguates_same_name_across_kinds(tmp_path):
    # The same stem under two kinds must resolve to the requested kind.
    for kind in ("machine", "filament"):
        d = tmp_path / "BBL" / kind
        d.mkdir(parents=True, exist_ok=True)
        (d / "Shared Name.json").write_text("{}", encoding="utf-8")
    m = _find_profile_json(tmp_path, "machine", "Shared Name")
    f = _find_profile_json(tmp_path, "filament", "Shared Name")
    assert "machine" in m.parts and "filament" not in m.parts
    assert "filament" in f.parts and "machine" not in f.parts


def test_find_profile_json_missing_raises(tmp_path):
    _profile_tree(tmp_path)
    with pytest.raises(OrcaProfileError, match="no process profile named"):
        _find_profile_json(tmp_path, "process", "Does Not Exist")


def test_resolve_maps_printer_material_to_three_jsons(tmp_path):
    root = _profile_tree(tmp_path)
    settings = resolve_slice_settings(root, _p2s(), _PLA)
    assert settings.machine.stem == "Bambu Lab P2S 0.4 nozzle"
    assert settings.process.stem == "0.20mm Standard @BBL P2S"
    assert settings.filament.stem == "Bambu PLA Basic @BBL P2S"
    for path, kind in (
        (settings.machine, "machine"),
        (settings.process, "process"),
        (settings.filament, "filament"),
    ):
        assert path.exists() and kind in path.parts


def test_resolve_unmapped_material_is_not_available(tmp_path):
    # A material with NO printer-specific filament entry is honestly "not available" on that
    # printer — there is no silent cross-vendor generic fallback (which could resolve to a
    # different vendor's profile and slice plausible-but-wrong G-code on the wrong machine).
    root = _profile_tree(tmp_path)
    with pytest.raises(OrcaProfileError, match="not available on printer"):
        resolve_slice_settings(root, _p2s(), _PETG)


def test_resolve_raises_when_no_process_profile(tmp_path):
    # A printer configured with no process profile must refuse with a clear error rather
    # than mis-slice. (This is the general mechanism; every shipped printer, Elegoo
    # included, actually has a process profile.)
    root = _profile_tree(tmp_path)
    no_proc = _p2s(orca_process_profile=None)
    with pytest.raises(OrcaProfileError, match="no OrcaSlicer process profile"):
        resolve_slice_settings(root, no_proc, _PLA)


def test_resolve_raises_when_no_machine_profile(tmp_path):
    root = _profile_tree(tmp_path)
    with pytest.raises(OrcaProfileError, match="no OrcaSlicer machine profile"):
        resolve_slice_settings(root, _p2s(orca_machine_profile=None), _PLA)


def test_resolve_raises_when_configured_name_missing(tmp_path):
    root = _profile_tree(tmp_path)
    bad = _p2s(orca_machine_profile="Nonexistent Machine 9.9 nozzle")
    with pytest.raises(OrcaProfileError, match="no machine profile named"):
        resolve_slice_settings(root, bad, _PLA)


def test_elegoo_tpu_is_honestly_not_available():
    # The Neptune 4 Max has no shipped TPU filament profile, so TPU is a clear "not available"
    # (raised before any file lookup), not a wrong-vendor generic. Config-only, no tree needed —
    # a dummy profiles root PROVES the error precedes any file lookup, and keeps this running
    # on machines without the bundled tools (orca_profiles_root() raises there).
    cfg = Config.load()
    with pytest.raises(OrcaProfileError, match="not available on printer"):
        resolve_slice_settings(
            Path("profiles-root-never-touched"),
            cfg.printer("elegoo_neptune_4_max"),
            cfg.material("tpu"),
        )


def _profiles_present() -> bool:
    try:
        return Config.load().orca_profiles_root().exists()
    except Exception:  # pragma: no cover - config absent
        return False


@pytest.mark.real_tool
@pytest.mark.skipif(not _profiles_present(), reason="OrcaSlicer profiles not fetched")
def test_every_configured_material_resolves_to_a_real_filament():
    # Each printer's configured per-material filament name resolves to a real shipped JSON —
    # catches a typo'd profile name (the Elegoo-class mistake) without a live slice.
    cfg = Config.load()
    root = cfg.orca_profiles_root()
    expected = {
        "bambu_p2s": {"pla", "petg", "tpu", "abs"},
        "bambu_a1": {"pla", "petg", "tpu", "abs"},
        "elegoo_neptune_4_max": {"pla", "petg", "abs"},  # no TPU profile ships for it
    }
    import json

    for pk, mats in expected.items():
        printer = cfg.printer(pk)
        assert set(printer.orca_filament_profiles) == mats, pk
        for mk in mats:
            settings = resolve_slice_settings(root, printer, cfg.material(mk))
            assert settings.filament.exists(), f"{pk}/{mk} -> {settings.filament}"
            # Guard the wrong-vendor bug-family: a name that resolves to a real file for a
            # DIFFERENT machine would slice plausible-but-wrong G-code. Require the resolved
            # filament to declare THIS printer's machine compatible.
            compat = json.loads(settings.filament.read_text(encoding="utf-8")).get(
                "compatible_printers"
            ) or []
            assert printer.orca_machine_profile in compat, (
                f"{pk}/{mk}: {settings.filament.name} not compatible with "
                f"{printer.orca_machine_profile}"
            )


@pytest.mark.real_tool
@pytest.mark.skipif(not _profiles_present(), reason="OrcaSlicer profiles not fetched")
def test_resolve_real_p2s_pla_profiles():
    """The configured Bambu P2S + PLA resolves to three real shipped JSON files."""
    cfg = Config.load()
    settings = resolve_slice_settings(
        cfg.orca_profiles_root(), cfg.printer("bambu_p2s"), cfg.material("pla")
    )
    assert settings.machine.exists()
    assert settings.process.exists()
    assert settings.filament.exists()


@pytest.mark.real_tool
@pytest.mark.skipif(not _profiles_present(), reason="OrcaSlicer profiles not fetched")
def test_resolve_real_all_three_printers_resolve():
    """All three of Kim's printers (P2S, A1, Elegoo Neptune 4 Max) resolve to three real
    shipped profile JSONs. (The Elegoo's process profiles ship as 'Neptune4Max' without
    spaces while its machine profile uses 'Neptune 4 Max' with spaces.)"""
    cfg = Config.load()
    for key in ("bambu_p2s", "bambu_a1", "elegoo_neptune_4_max"):
        settings = resolve_slice_settings(
            cfg.orca_profiles_root(), cfg.printer(key), cfg.material("pla")
        )
        assert settings.machine.exists(), key
        assert settings.process.exists(), key
        assert settings.filament.exists(), key


# --- prove_gcode_3mf (G-code proof) -------------------------------------------


def test_prove_gcode_accepts_real_toolpath(tmp_path):
    p = tmp_path / "part.gcode.3mf"
    _write_gcode_3mf(p)
    proof = prove_gcode_3mf(p)
    assert proof.has_motion
    assert proof.entries == ("Metadata/plate_1.gcode",)
    assert proof.line_count == len(_GCODE.splitlines())
    # the slicer print estimate is parsed out of the G-code header
    assert proof.estimated_time == "14m 45s"
    assert proof.layer_count == 100
    assert proof.filament_mm == 2582.09
    assert proof.filament_cm3 == 6.21
    assert proof.filament_g == 7.62
    summary = proof.estimate_summary()
    # weight is the friendliest filament figure, so the summary leads with grams (and the cm3
    # is superseded — not appended twice).
    assert "14m 45s" in summary and "100 layers" in summary and "7.6 g" in summary
    assert "cm3" not in summary
    # the structured breakout carries every field for the UI to lay out as labeled stats
    detail = proof.estimate_detail()
    assert detail == {
        "time": "14m 45s",
        "layers": 100,
        "filament_mm": 2582.09,
        "filament_cm3": 6.21,
        "filament_g": 7.62,
    }


def test_prove_gcode_parses_bambu_weight_wording(tmp_path):
    # Bambu profiles spell the weight differently ("total filament weight [g] : N") — the
    # estimate must still pick it up so Kim's Bambu P2S reports a weight, not a blank.
    p = tmp_path / "bambu.gcode.3mf"
    _write_gcode_3mf(
        p,
        gcode=(
            "; total layer number: 42\n"
            "; total filament weight [g] : 12.30\n"
            "G1 X1 Y1 E0.1\n"
        ),
    )
    proof = prove_gcode_3mf(p)
    assert proof.filament_g == 12.30
    assert proof.layer_count == 42
    assert "12.3 g" in proof.estimate_summary()


def test_estimate_detail_omits_unreported_fields(tmp_path):
    # A profile that emits no estimate lines yields an all-None detail (the UI shows no rows
    # rather than fabricated zeros) and an empty summary.
    p = tmp_path / "bare.gcode.3mf"
    _write_gcode_3mf(p, gcode="G1 X1 Y1 E0.1\nG1 X2 Y2 E0.2\n")
    proof = prove_gcode_3mf(p)
    assert proof.estimate_detail() == {
        "time": None,
        "layers": None,
        "filament_mm": None,
        "filament_cm3": None,
        "filament_g": None,
    }
    assert proof.estimate_summary() == ""


def test_prove_gcode_rejects_non_zip(tmp_path):
    p = tmp_path / "not.3mf"
    p.write_bytes(b"plain text, not a zip")
    with pytest.raises(SliceFailed, match="not a valid 3MF"):
        prove_gcode_3mf(p)


def test_prove_gcode_rejects_missing_gcode_member(tmp_path):
    p = tmp_path / "empty.gcode.3mf"
    _write_gcode_3mf(p, gcode=None)
    with pytest.raises(SliceFailed, match="no .gcode toolpath member"):
        prove_gcode_3mf(p)


def test_prove_gcode_rejects_motionless_gcode(tmp_path):
    # G-code present but only setup/home (M104/M140/G92/G10/G28) — the \b boundary in the
    # motion regex must NOT mistake G10/G28/G92 for a G0-3 move (TEST-007 negative case).
    p = tmp_path / "motionless.gcode.3mf"
    _write_gcode_3mf(p, gcode="; header only\nM104 S210\nG28\nG92 E0\nG10\n")
    with pytest.raises(GcodeProofFailed, match="no motion"):
        prove_gcode_3mf(p)


def test_prove_gcode_accepts_arc_only_motion(tmp_path):
    # TEST-007 positive: an arc-fitted toolpath whose only motion is G2/G3 must pass.
    p = tmp_path / "arc.gcode.3mf"
    _write_gcode_3mf(p, gcode="; arc part\nG28\nG2 X10 Y10 I5 J0\nG3 X0 Y0 I-5 J0\n")
    proof = prove_gcode_3mf(p)
    assert proof.has_motion


def test_prove_gcode_failure_message_has_no_exited_prefix(tmp_path):
    # QA-006: a proof failure must not claim "orca-slicer exited 0" (it didn't fail there).
    p = tmp_path / "notzip.3mf"
    p.write_bytes(b"not a zip")
    with pytest.raises(GcodeProofFailed) as exc:
        prove_gcode_3mf(p)
    assert "exited" not in str(exc.value)
    assert isinstance(exc.value, SliceFailed)  # still a SliceFailed for existing handlers


def test_prove_gcode_rejects_too_many_members(tmp_path, monkeypatch):
    # ENG-002: an archive with an implausible number of .gcode members is rejected.
    monkeypatch.setattr(slicer_mod, "_MAX_GCODE_MEMBERS", 2)
    p = tmp_path / "many.gcode.3mf"
    with zipfile.ZipFile(p, "w") as zf:
        for i in range(3):
            zf.writestr(f"Metadata/plate_{i}.gcode", "G1 X1 Y1\n")
    with pytest.raises(GcodeProofFailed, match="implausible number"):
        prove_gcode_3mf(p)


def test_prove_gcode_rejects_oversize_member(tmp_path, monkeypatch):
    # ENG-002: a member whose uncompressed size exceeds the cap is rejected before walking.
    monkeypatch.setattr(slicer_mod, "MAX_GCODE_MEMBER_BYTES", 8)
    p = tmp_path / "big.gcode.3mf"
    _write_gcode_3mf(p, gcode="G1 X10 Y10 E1\nG1 X20 Y20 E2\n" * 4)
    with pytest.raises(GcodeProofFailed, match="too large"):
        prove_gcode_3mf(p)


def test_estimate_mm_only_fallback(tmp_path):
    # TEST-006: when the slicer emits filament [mm] but not [cm3], the mm fallback is used.
    p = tmp_path / "mm.gcode.3mf"
    _write_gcode_3mf(
        p, gcode="; total layer number: 10\n; filament used [mm] = 1234.5\nG28\nG1 X1 Y1 E1\n"
    )
    proof = prove_gcode_3mf(p)
    assert proof.filament_cm3 is None
    assert proof.filament_mm == 1234.5
    assert "1234 mm filament" in proof.estimate_summary()


def test_estimate_absent_yields_empty_summary(tmp_path):
    # TEST-006: motion-bearing G-code with no estimate comments -> empty summary.
    p = tmp_path / "noest.gcode.3mf"
    _write_gcode_3mf(p, gcode="; nothing useful\nG28\nG1 X1 Y1 E1\n")
    proof = prove_gcode_3mf(p)
    assert proof.estimated_time is None and proof.layer_count is None
    assert proof.estimate_summary() == ""


def test_estimate_time_fallback_to_model_printing_time(tmp_path):
    # TEST-011: when only "model printing time" is present (no "total estimated time").
    p = tmp_path / "fb.gcode.3mf"
    _write_gcode_3mf(p, gcode="; model printing time: 14m 31s\nG28\nG1 X1 Y1 E1\n")
    proof = prove_gcode_3mf(p)
    assert proof.estimated_time == "14m 31s"


def test_estimate_time_normal_mode_format(tmp_path):
    # The Elegoo / PrusaSlicer-derived header form: "estimated printing time (normal mode)".
    p = tmp_path / "nm.gcode.3mf"
    _write_gcode_3mf(
        p, gcode="; estimated printing time (normal mode) = 33m 23s\nG28\nG1 X1 Y1 E1\n"
    )
    proof = prove_gcode_3mf(p)
    assert proof.estimated_time == "33m 23s"


def test_estimate_time_primary_stops_at_semicolon(tmp_path):
    # ENG-001: "total estimated time:" followed by another clause must capture only the
    # time, not greedily to end-of-line.
    p = tmp_path / "multi.gcode.3mf"
    _write_gcode_3mf(p, gcode="; total estimated time: 14m 45s; foo: bar\nG28\nG1 X1 Y1 E1\n")
    proof = prove_gcode_3mf(p)
    assert proof.estimated_time == "14m 45s"


def test_estimate_ignores_first_layer_time(tmp_path):
    # The "estimated first layer printing time (normal mode)" line must NOT be mistaken
    # for the whole-print estimate (it isn't the substring "estimated printing time").
    p = tmp_path / "fl.gcode.3mf"
    _write_gcode_3mf(
        p,
        gcode="; estimated first layer printing time (normal mode) = 22s\nG28\nG1 X1 Y1 E1\n",
    )
    proof = prove_gcode_3mf(p)
    assert proof.estimated_time is None


def test_find_profile_json_ambiguous_name_raises(tmp_path):
    # TEST-005 / ENG-007 / QA-004: the same name+kind under two vendors must fail loud,
    # not silently slice with the first-sorted vendor's profile.
    for vendor in ("BBL", "Creality"):
        d = tmp_path / vendor / "filament"
        d.mkdir(parents=True, exist_ok=True)
        (d / "Generic PLA.json").write_text("{}", encoding="utf-8")
    with pytest.raises(OrcaProfileError, match="ambiguous"):
        _find_profile_json(tmp_path, "filament", "Generic PLA")


# --- live end-to-end slice through the real OrcaSlicer ------------------------


def _binary_and_profiles_present() -> bool:
    try:
        cfg = Config.load()
        return cfg.binary_path("orcaslicer").exists() and cfg.orca_profiles_root().exists()
    except Exception:  # pragma: no cover - config/binary absent
        return False


@pytest.mark.live  # TEST-008: invokes the real OrcaSlicer; `pytest -m "not live"` skips it
@pytest.mark.skipif(
    not _binary_and_profiles_present(), reason="OrcaSlicer binary/profiles not present"
)
@pytest.mark.parametrize("printer_key", [
    # The 3 reference printers, PLUS one representative per #22 curated vendor: a per-vendor slice
    # smoke that catches profile-format / G-code-header regressions across the makers without
    # slicing all 29 catalogued printers on every push. The FULL curated catalog is slice-proven
    # (each machine + each material) by scripts/build_printer_catalog.py --verify, the recorded
    # proof of record; KC-7 re-verifies every printer's build volume on every run.
    "bambu_p2s", "bambu_a1", "elegoo_neptune_4_max",
    "bambu_p1s", "creality_k1", "prusa_mk4", "anycubic_kobra2", "elegoo_neptune4",
    "qidi_q1_pro", "sovol_sv06",
])
def test_live_slice_box_produces_proven_gcode(tmp_path, printer_key):
    """The whole chain, live, for the reference printers + a representative of each curated
    vendor: resolve the configured profiles, slice a real 20 mm box through the bundled
    OrcaSlicer, and prove the exported 3MF carries a real motion-bearing toolpath WITH a parsed
    estimate (time + layers + filament). No mocks, real binary, real profiles, real mesh — the
    high-altitude regression anchor for slicing, across vendors whose G-code headers use
    different time/profile-naming conventions."""
    import trimesh

    cfg = Config.load()
    settings = resolve_slice_settings(
        cfg.orca_profiles_root(), cfg.printer(printer_key), cfg.material("pla")
    )
    stl = tmp_path / "box.stl"
    trimesh.creation.box(extents=[20, 20, 20]).export(str(stl))

    res = slice_model(
        stl,
        binary=cfg.binary_path("orcaslicer"),
        out_dir=tmp_path,
        settings=settings,
        basename="box",
        timeout_s=300,
    )
    assert res.gcode_path.exists()
    assert res.gcode_proof is not None
    assert res.gcode_proof.has_motion
    assert res.gcode_proof.line_count > 100  # a real toolpath, not a near-empty stub
    # the real OrcaSlicer output carries a print estimate (Stage 1 exit criterion).
    # TEST-010: a 20mm box at 0.2mm layers is ~100 layers; >= 90 is a real lower bound
    # that a near-empty-toolpath profile regression would breach (not just "non-empty").
    # The time estimate must parse for every printer (the Elegoo header format is the one
    # that originally went unparsed).
    assert res.gcode_proof.estimated_time, f"{printer_key}: no time estimate parsed"
    assert res.gcode_proof.layer_count and res.gcode_proof.layer_count >= 90
    assert res.gcode_proof.filament_mm and res.gcode_proof.filament_mm > 0
